definitions:
  data.GameSess:
    properties:
      data:
        type: string
      gid:
        type: integer
      gtid:
        type: string
      time:
        type: integer
      uid:
        type: string
    required:
    - data
    - gid
    - gtid
    - time
    - uid
    type: object
  handler.GameHistoryResFail:
    properties:
      message:
        type: string
      status:
        type: string
    type: object
  handler.GameHistoryResOk:
    properties:
      page: {}
      status:
        type: string
    type: object
info:
  contact: {}
paths:
  /game/history/{gid}:
    get:
      description: handles the retrieval of game history for a given game ID. It paginates
        the results based on the page and pageSize query parameters.
      parameters:
      - description: Game ID
        in: path
        name: gid
        required: true
        type: string
      - description: Page number
        in: query
        name: page
        type: string
      - description: Page size
        in: query
        name: pageSize
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.GameHistoryResOk'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.GameHistoryResFail'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handler.GameHistoryResFail'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.GameHistoryResFail'
      summary: Show game history
      tags:
      - game history
  /game/history/user/{uid}:
    get:
      description: handles the retrieval of game history for a given user ID. It paginates
        the results based on the page and pageSize query parameters.
      parameters:
      - description: User ID
        in: path
        name: uid
        required: true
        type: string
      - description: Page number
        in: query
        name: page
        type: string
      - description: Page size
        in: query
        name: pageSize
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.GameHistoryResOk'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.GameHistoryResFail'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handler.GameHistoryResFail'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.GameHistoryResFail'
      summary: Show user game history
      tags:
      - user game history
  /game/store:
    post:
      consumes:
      - application/json
      description: stores game data in the game history handler.
      parameters:
      - description: Game data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/data.GameSess'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.GameHistoryResOk'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.GameHistoryResFail'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handler.GameHistoryResFail'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.GameHistoryResFail'
      summary: Store game data
      tags:
      - game history
swagger: "2.0"
